# -*- coding: utf-8 -*-
"""
/***************************************************************************
 PixelCalculator
                                 A QGIS plugin
 Calculate the average value of selected pixels of a raster layer.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-09-29
        copyright            : (C) 2022 by Roel Huybrechts
        email                : roel@huybrechts.re
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load PixelCalculator class from file PixelCalculator.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .pixel_calculator import PixelCalculator
    return PixelCalculator(iface)
